export const RESET_LIST = 'RESET_DESIGNS'

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE'

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

export const UPDATE_DELIVERY_STATUS = 'UPDATE_DELIVERY_STATUS'

export const ADD_DELIVERY = 'ADD_DELIVERY'
